travis:
  secure:
    BINSTAR_TOKEN: uzk4qbzo6GO3E8j8Nh0naIIFXjHP4Be4pEy2uGnnxOnooLAcRP9OLAYwBnatVf8KUoiaZUH+K3MouZGxOUOqgw2JZ93Dyb5LRQX3+dZr2K0Nu+CxrQ1lTqWxBx75GcHfPA2fMU11b57JheRZ+qHl8yky6fDVRaz1vPS/Wilc8N0xoq5X5aecbTEEqiHdNYg2t1f8XZGIUa1b394vKyLEM6c2vNfRgLjcHWlJVn6lgaIZpGPhL8r8rnGfkHhaHQJ6lHTh9lWUFut5dDE7K6FS4iFi/DgrgJ7ESfbi0sCIX72L2ZWM6E7hUmHuilqy2R9VBqFK/cuhbrYI/NA1z4pGreqWSxmRNqwECX+pSWN1JiTx+GKtTXMb4ABMmzBTG/r3z5xS3YXxo5s5NF/BvK5Qf+hh7QtgazB60CXn/Ip/wD6L/yvs2h5bsDdkhgkBxEh/Gzo3V2MGK5keuQv8lhDEPQ/12EYlOLcMIGz8TePEGXhNr//G0MRFAPb/lXbjsLFBFsaMbOcuG9Pap/A1jtGozR6iFcaHngYoUlNg3T6HIySeveT0KGprdOjo/yfOMCUX3OtEVaVU/DG0z/Whh6/GDVZUC6SVfMZA14mXovAfRa66zl8GDZuLqMr/UIRTt+w3oKeU2aOTAXkWiKvRm59pfh395KSRrypbJrIXhtiaAD0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
