travis:
  secure:
    BINSTAR_TOKEN: Q00/IYmbnpJgKssW/65wGneuFbbhYrkHcnCAHX8zDj1I6LC1x3RDQf+O5imLKpsEvhhx1M86B2R9LPg8ixpyNwsk9ugKM3ISrBAuhCOpq2xO80Wikdps++H5hbfPqbLRFxqDAN4qIlgTpZ0HSyZR2GSK3vNtI2wtbbBJ+Uv25JYB2brnU+ILzRgpl2i51kgGJT93xf2tmcwFAnaA7tQpWs0xaa3QKX6MWemFbT1pOHmbD2wdWvm8rAa0+9ph/iWb5meevTRba/P+2DPMQ5VUxf1Ys5j+KAhHJHBDWyfSzHFV/V6rGANDGu6jimZzEZJ7QC6ezkIJ34dOpj5RiDBaCtGv5EiX2nf0BfTJLadiTOd0w+I1a1tPBqi7gUlynzS6tdT1NPG+GG4IipFYa8u/D3TZTTuvVMSLR9JdN2wmZMesddjWNiS8AgJeIp3Cn0QxaVOoff58gVUEIOuKj+GPhMRMLm+QoJ0v9L9ExyBicLHbtk7R8Fb9DElQR44P639AtYKxnFYbDWDkyijFJrhoIng7X0JDBK9rva6K3b0lGS+LC+QmFkxJx1a5Ubcofow+rktSvMJnxAO6Ddti68HOy0Gta/om/a13qOFNseDEJxNbqS45/YhgvhyBXgduJDQVgUXD7kJ6nuVQCT4Au1sAtDdHM/wjy+hbaa5tfEGQ6dg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
