travis:
  secure:
    BINSTAR_TOKEN: pYHpa9tNbM47fOxp+cIyP+XskOW07HTvSdwi06kBSlFv/FhTHmDcibnuvsLAiFmWmeUW44nlsmEUaB3BiDFbdNg3hpo2QGRFJIlcIrkd26pxJdFhFbjQQDOarWwplgTUsmcAbnAJ7iJuRDK8UnUPaij3ZxNrL3kUluM0gb3OxuT4xTKZnyyii9jM4Gyq+GCI8KVS8t2hZDyiXBUW42j2ECdlaAiPFgaYbpKMrwuGEbae4fDQM+TzBypw1Cz/mK7juxVnnywnFcbUC+vzSv4r546+h51bj/4MKdLCCBSwdKSl8JiViZNw9yslcPak13ETjsSZm3bCMGEzsRyax9z39ryyeMHE7AGnthWScaiEgRsARH3C+CNeLZGtMUi4a+CyPdMTWgO1BcE76w5ZXqUozwJfGDWvYC345LAks7IBgVWtf3YEVzuAzBTYWdLMVBznJZF0ptCur9mTgu7Gd3tXcXBPjj77k/y9KehycsmR9PZ734hCyGjNE+QrjAoqLyT9w4L32nu1u2YjjDNccfp6TmWji1u21NRBJV2pPHdwYDnjukD9vqGivy91CKLGtGCV03oGb7fmV1F6AxvWh8TFTuR2m4CoPlSVkQcj3VwvNv89AdsYkfkDezNZvpQU+EWBdR3HshhFR3YZZYNrZrWS6u5zGaLEoDjuLheGomadi1M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
